export type Tracking = 'weight_reps' | 'reps' | 'time' | 'distance_time';
export interface Exercise { id: string; slug?: string | null; name: string; nameDesi?: string | null; category: string; muscleGroup?: string | null; equipment?: string | null; difficulty?: string | null; type?: string | null; tracking: Tracking; isCustom: boolean; userId?: string | null; videoUrl?: string | null }
export interface WSet { id?: string; exerciseId: string; setNumber: number; reps?: number | null; weight?: number | null; durationSec?: number | null; distanceM?: number | null; rpe?: number | null; restSec?: number | null; isWarmup?: boolean }
export interface Session { id: string; routineId?: string | null; name?: string | null; type?: string | null; date: string; duration?: number | null; notes?: string | null; sessionRpe?: number | null; readiness?: Record<string, number> | null; warmupDone?: boolean; cooldownDone?: boolean; sets: WSet[]; newPRs?: PR[] }
export interface PR { id: string; exerciseId: string; type: string; value: number; unit?: string | null; reps?: number | null; weight?: number | null; date: string; previous?: number | null }
export interface RoutineExercise { id?: string; exerciseId: string; sets?: number | null; reps?: number | null; weight?: number | null; durationSec?: number | null; distanceM?: number | null; restSec?: number | null; rpe?: number | null; notes?: string | null }
export interface Routine { id: string; name: string; type: string; focus?: string | null; notes?: string | null; estDuration?: number | null; days: number[]; blocks: { id?: string; name: string; exercises: RoutineExercise[] }[] }
export interface Goal { id: string; type: string; priority: 'primary' | 'secondary'; startDate: string; targetDate?: string | null; eventDate?: string | null; targetWeight?: number | null; phaseName?: string | null; active: boolean }
export interface Suggestion { id: string; type: string; priority: 'high' | 'medium' | 'low'; message: string; action?: unknown }
export interface Settings { languageMode: 'desi' | 'en' | 'hi'; tone: string; theme: 'dark' | 'light'; units: 'metric' | 'imperial'; aiEnabled: boolean; aiAvailable?: boolean; calorieTarget?: number | null; proteinTarget?: number | null; waterTargetMl?: number | null; region?: string | null; festivalMode?: string | null; user?: { email: string; name?: string | null } }
export interface Food { key: string; name: string; category: string; unit: string; cal: number; p: number; c: number; f: number }
export interface Flow { id: string; name: string; type: string; sport?: string; steps: { name: string; durationSec?: number; reps?: number; note?: string }[] }
